// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// import_fasta_to_vector_each_nt
List import_fasta_to_vector_each_nt(std::string file);
RcppExport SEXP _pairsnp_import_fasta_to_vector_each_nt(SEXP fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type file(fileSEXP);
    rcpp_result_gen = Rcpp::wrap(import_fasta_to_vector_each_nt(file));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pairsnp_import_fasta_to_vector_each_nt", (DL_FUNC) &_pairsnp_import_fasta_to_vector_each_nt, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_pairsnp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
