# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

import_fasta_to_vector_each_nt <- function(file) {
    .Call('_pairsnp_import_fasta_to_vector_each_nt', PACKAGE = 'pairsnp', file)
}

